/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WidgetsWeddingRouteImport } from './routes/widgets/wedding'
import { Route as WidgetsNuscRouteImport } from './routes/widgets/nusc'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetsWeddingRoute = WidgetsWeddingRouteImport.update({
  id: '/widgets/wedding',
  path: '/widgets/wedding',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetsNuscRoute = WidgetsNuscRouteImport.update({
  id: '/widgets/nusc',
  path: '/widgets/nusc',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/widgets/nusc': typeof WidgetsNuscRoute
  '/widgets/wedding': typeof WidgetsWeddingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/widgets/nusc': typeof WidgetsNuscRoute
  '/widgets/wedding': typeof WidgetsWeddingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/widgets/nusc': typeof WidgetsNuscRoute
  '/widgets/wedding': typeof WidgetsWeddingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/widgets/nusc' | '/widgets/wedding'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/widgets/nusc' | '/widgets/wedding'
  id: '__root__' | '/' | '/about' | '/widgets/nusc' | '/widgets/wedding'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  WidgetsNuscRoute: typeof WidgetsNuscRoute
  WidgetsWeddingRoute: typeof WidgetsWeddingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widgets/wedding': {
      id: '/widgets/wedding'
      path: '/widgets/wedding'
      fullPath: '/widgets/wedding'
      preLoaderRoute: typeof WidgetsWeddingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widgets/nusc': {
      id: '/widgets/nusc'
      path: '/widgets/nusc'
      fullPath: '/widgets/nusc'
      preLoaderRoute: typeof WidgetsNuscRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  WidgetsNuscRoute: WidgetsNuscRoute,
  WidgetsWeddingRoute: WidgetsWeddingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
